"""
YAML generation module for HTML-to-YAML extraction pipeline.

This module provides the final step of the extraction pipeline, taking
validated ExtractedRule objects from the adjudicator and generating a
schema-compliant YAML file suitable for distribution.

Key Features:
- Preserves all extraction metadata fields (expert_source, anchor_id, confidence_score)
- Wraps rules in RuleSet with schema version and extraction timestamp
- Adds generation metadata header to output file
- Performs read-back verification to ensure file integrity
- Comprehensive error handling with single exception type

Usage:
    >>> from qe_tax_rag.extraction.ca.yaml_generator import generate
    >>> from qe_tax_rag.extraction.ca.schema import ExtractedRule
    >>>
    >>> rules = [...]  # List of ExtractedRule from adjudicator
    >>> generate(rules=rules, output_path="output/cra_rules.yml")

Integration:
    This module is called by the orchestrator (TICKET 6) after adjudication
    completes. It receives the final, validated list of rules and produces
    the deployable YAML artifact.

Error Handling:
    All errors raise YAMLGenerationError, which should be caught by the
    orchestrator for proper error reporting to the user.
"""

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Final

import yaml
from pydantic import ValidationError

from qe_tax_rag import __version__
from qe_tax_rag.extraction.ca.exceptions import YAMLGenerationError
from qe_tax_rag.extraction.ca.schema import ExtractedRule, RuleSet

logger: logging.Logger = logging.getLogger(__name__)

# Internal metadata fields to exclude from final YAML output
# NOTE: Previously excluded fields are now REQUIRED for database building
# These fields provide crucial observability for RAG quality analysis
_INTERNAL_METADATA_FIELDS: Final[set[str]] = {
    # "expert_source",     # REQUIRED for database metadata (extraction_source)
    # "anchor_id",         # REQUIRED for database metadata (source_anchor)
    # "confidence_score",  # REQUIRED for database metadata (extraction_confidence)
}

# Schema version for generated YAML files
_SCHEMA_VERSION: Final[str] = "1.0"

# YAML formatting parameters
_YAML_LINE_WIDTH: Final[int] = 88  # Match project line length standard


def generate(rules: list[ExtractedRule], output_path: str) -> None:
    """
    Generate schema-compliant YAML file from validated rules.

    Args:
        rules: List of validated ExtractedRule objects from adjudicator.
        output_path: Path for output YAML file.

    Raises:
        YAMLGenerationError: If file cannot be written or verified.

    """
    try:
        # Create parent directories
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now(timezone.utc).isoformat()

        # Create RuleSet with required fields
        rule_set = RuleSet(
            schema_version=_SCHEMA_VERSION,
            extraction_timestamp=timestamp,
            rules=rules,
        )

        # Convert to dict with enums as strings, excluding internal metadata
        # Use JSON roundtrip for enum conversion
        data = json.loads(
            rule_set.model_dump_json(
                exclude={"rules": {"__all__": _INTERNAL_METADATA_FIELDS}}
                if _INTERNAL_METADATA_FIELDS
                else None
            )
        )

        # Serialize to YAML
        yaml_string = yaml.dump(
            data,
            sort_keys=False,
            default_flow_style=False,
            allow_unicode=True,
            width=_YAML_LINE_WIDTH,
        )

        # Prepend header with generation metadata
        header = (
            f"# Generated by qe-tax-rag version {__version__} on {timestamp}\n"
            f"# Do not edit this file manually. Changes will be overwritten.\n"
            f"---\n"
        )

        # Write to file
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(header)
            f.write(yaml_string)

        logger.info(
            "Successfully wrote YAML file",
            extra={"output_path": output_path},
        )

        # Read-back verification
        logger.info(
            "Performing read-back verification",
            extra={"output_path": output_path},
        )

        with open(output_path, encoding="utf-8") as f:
            content = f.read()
            # Skip header lines (everything before ---)
            if "---\n" in content:
                yaml_content = content.split("---\n", 1)[1]
            else:
                yaml_content = content
            read_back_data = yaml.safe_load(yaml_content)

        # Basic validation: Check structure exists
        if not isinstance(read_back_data, dict):
            msg = f"YAML verification failed - invalid structure in {output_path}"
            raise YAMLGenerationError(msg)
        if "rules" not in read_back_data:
            msg = f"YAML verification failed - missing 'rules' key in {output_path}"
            raise YAMLGenerationError(msg)
        if "schema_version" not in read_back_data:
            msg = (
                f"YAML verification failed - missing 'schema_version' key "
                f"in {output_path}"
            )
            raise YAMLGenerationError(msg)

        logger.info(
            "YAML verification successful",
            extra={"output_path": output_path},
        )

    except PermissionError as e:
        msg = f"Failed to write YAML file to {output_path}: Permission denied"
        logger.exception(msg)
        raise YAMLGenerationError(msg) from e
    except FileNotFoundError as e:
        msg = f"File disappeared during verification: {output_path}"
        logger.exception(msg)
        raise YAMLGenerationError(msg) from e
    except OSError as e:
        msg = f"Failed to write YAML file to {output_path}: {e}"
        logger.exception(msg)
        raise YAMLGenerationError(msg) from e
    except yaml.YAMLError as e:
        msg = f"YAML verification failed - invalid syntax in {output_path}"
        logger.exception(msg)
        raise YAMLGenerationError(msg) from e
    except ValidationError as e:
        msg = f"YAML verification failed - schema mismatch in {output_path}: {e}"
        logger.exception(msg)
        raise YAMLGenerationError(msg) from e
