"""YAML generation module for HTML-to-YAML extraction pipeline.

This module takes validated ExtractedRule objects and generates a
schema-compliant YAML file with metadata stripping, RuleSet wrapping,
and read-back verification.
"""

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Final

import yaml
from pydantic import ValidationError

from qe_tax_rag import __version__
from qe_tax_rag.extraction.ca.exceptions import YAMLGenerationError
from qe_tax_rag.extraction.ca.schema import ExtractedRule, RuleSet

logger: logging.Logger = logging.getLogger(__name__)

# Internal metadata fields to exclude from final YAML output
_INTERNAL_METADATA_FIELDS: Final[set[str]] = {
    "expert_source",    # Tracks which expert generated the rule
    "anchor_id",        # HTML anchor ID for debugging
    "confidence_score", # Adjudicator confidence metric
}

# Schema version for generated YAML files
_SCHEMA_VERSION: Final[str] = "1.0"

# YAML formatting parameters
_YAML_LINE_WIDTH: Final[int] = 88  # Match project line length standard


def generate(rules: list[ExtractedRule], output_path: str) -> None:
    """Generate schema-compliant YAML file from validated rules.

    Args:
        rules: List of validated ExtractedRule objects from adjudicator.
        output_path: Path for output YAML file.

    Raises:
        YAMLGenerationError: If file cannot be written or verified.
    """
    try:
        # Create parent directories
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now(timezone.utc).isoformat()

        # Create RuleSet with required fields
        rule_set = RuleSet(
            schema_version=_SCHEMA_VERSION,
            extraction_timestamp=timestamp,
            rules=rules,
        )

        # Convert to dict with enums as strings, excluding internal metadata
        # Use JSON roundtrip for enum conversion
        data = json.loads(rule_set.model_dump_json(exclude={"rules": {"__all__": _INTERNAL_METADATA_FIELDS}}))

        # Serialize to YAML
        yaml_string = yaml.dump(
            data,
            sort_keys=False,
            default_flow_style=False,
            allow_unicode=True,
            width=_YAML_LINE_WIDTH,
        )

        # Prepend header with generation metadata
        header = (
            f"# Generated by qe-tax-rag version {__version__} on {timestamp}\n"
            f"# Do not edit this file manually. Changes will be overwritten.\n"
            f"---\n"
        )

        # Write to file
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(header)
            f.write(yaml_string)

        logger.info(
            "Successfully wrote YAML file",
            extra={"output_path": output_path},
        )

        # Read-back verification
        logger.info(
            "Performing read-back verification",
            extra={"output_path": output_path},
        )

        with open(output_path, encoding="utf-8") as f:
            content = f.read()
            # Skip header lines (everything before ---)
            yaml_content = content.split("---\n", 1)[1] if "---\n" in content else content
            read_back_data = yaml.safe_load(yaml_content)

        # Basic validation: Check structure exists
        if not isinstance(read_back_data, dict):
            msg = f"YAML verification failed - invalid structure in {output_path}"
            raise YAMLGenerationError(msg)
        if "rules" not in read_back_data:
            msg = f"YAML verification failed - missing 'rules' key in {output_path}"
            raise YAMLGenerationError(msg)
        if "schema_version" not in read_back_data:
            msg = f"YAML verification failed - missing 'schema_version' key in {output_path}"
            raise YAMLGenerationError(msg)

        logger.info(
            "YAML verification successful",
            extra={"output_path": output_path},
        )

    except PermissionError as e:
        msg = f"Failed to write YAML file to {output_path}: Permission denied"
        logger.error(msg, exc_info=True)
        raise YAMLGenerationError(msg) from e
    except OSError as e:
        msg = f"Failed to write YAML file to {output_path}: {e}"
        logger.error(msg, exc_info=True)
        raise YAMLGenerationError(msg) from e
    except FileNotFoundError as e:
        msg = f"File disappeared during verification: {output_path}"
        logger.error(msg, exc_info=True)
        raise YAMLGenerationError(msg) from e
    except yaml.YAMLError as e:
        msg = f"YAML verification failed - invalid syntax in {output_path}"
        logger.error(msg, exc_info=True)
        raise YAMLGenerationError(msg) from e
    except ValidationError as e:
        msg = f"YAML verification failed - schema mismatch in {output_path}: {e}"
        logger.error(msg, exc_info=True)
        raise YAMLGenerationError(msg) from e
