"""Integration test for YAML generator with actual schema from Tickets 1-4."""

from pathlib import Path

import pytest
import yaml

from qe_tax_rag.extraction.ca import generate
from src.qe_tax_rag.extraction.ca.schema import ApplicabilityType, ExtractedRule, ExpertSource


@pytest.mark.integration
def test_yaml_generator_integration_with_schema(tmp_path: Path) -> None:
    """
    Integration test: Verify yaml_generator works with actual schema.

    This test validates that TICKET 5 integrates correctly with:
    - TICKET 1: ExtractedRule schema
    - TICKET 2: Classic parser expert source
    - TICKET 3: LLM parser expert source
    - TICKET 4: Adjudicator expert source and confidence scores
    """
    # Create sample rules using actual schema from TICKET 1-4
    rules = [
        ExtractedRule(
            rule_number=8523,
            title="Meals and entertainment",
            content="You can deduct 50% of eligible meal and entertainment expenses.",
            applies_to=[ApplicabilityType.BUSINESS],
            source_citation="Line 8523",
            chapter="Chapter 3 – Expenses",
            section="Part 4 – Net income (loss) before adjustments",
            source_file="t4002-5.html",
            expert_source=ExpertSource.CLASSIC,
            anchor_id="tocch3ln8523",
            confidence_score=0.95,
        ),
        ExtractedRule(
            rule_number=9270,
            title="Professional fees",
            content="You can deduct fees paid for professional services.",
            applies_to=[ApplicabilityType.BUSINESS, ApplicabilityType.FARMING],
            source_citation="Line 9270",
            chapter="Chapter 3 – Expenses",
            section="Part 4 – Net income (loss) before adjustments",
            source_file="t4002-5.html",
            expert_source=ExpertSource.ADJUDICATED,
            anchor_id="tocch3ln9270",
            confidence_score=0.88,
        ),
    ]

    output_path = tmp_path / "integration_test_output.yml"

    # Call the generate function (now exported from package)
    generate(rules=rules, output_path=str(output_path))

    # Verify file was created
    assert output_path.exists()

    # Read and validate YAML
    with open(output_path, encoding="utf-8") as f:
        content = f.read()

    # Verify header
    assert "# Generated by qe-tax-rag" in content
    assert "# Do not edit this file manually" in content

    # Parse YAML (skip header)
    yaml_content = content.split("---\n", 1)[1]
    data = yaml.safe_load(yaml_content)

    # Verify RuleSet structure
    assert "schema_version" in data
    assert data["schema_version"] == "1.0"
    assert "extraction_timestamp" in data
    assert "rules" in data
    assert len(data["rules"]) == 2

    # Verify internal metadata was stripped
    for rule in data["rules"]:
        assert "expert_source" not in rule  # Internal metadata
        assert "anchor_id" not in rule  # Internal metadata
        assert "confidence_score" not in rule  # Internal metadata

    # Verify required fields are present
    assert data["rules"][0]["rule_number"] == 8523
    assert data["rules"][0]["title"] == "Meals and entertainment"
    assert data["rules"][1]["rule_number"] == 9270
    assert data["rules"][1]["title"] == "Professional fees"

    # Verify enum was serialized as string
    assert data["rules"][0]["applies_to"] == ["business"]
    assert data["rules"][1]["applies_to"] == ["business", "farming"]
