"""Report generator for PDF coverage validation.

Generates JSON and markdown reports from classification results.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from scripts.pdf_coverage.models import CoverageReport, PageClassification

logger = logging.getLogger(__name__)


def generate_reports(
    report: CoverageReport,
    output_dir: str | Path,
) -> dict[str, Path]:
    """Generate all coverage reports (JSON + markdown).

    Args:
        report: Coverage report data
        output_dir: Directory to write reports

    Returns:
        Dictionary mapping report type to file path

    Raises:
        OSError: If report writing fails

    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    report_files: dict[str, Path] = {}

    # Generate keep_pages.json
    keep_pages_path = output_dir / "keep_pages.json"
    _write_keep_pages_json(report, keep_pages_path)
    report_files["keep_pages"] = keep_pages_path

    # Generate discard_pages.json
    discard_pages_path = output_dir / "discard_pages.json"
    _write_discard_pages_json(report, discard_pages_path)
    report_files["discard_pages"] = discard_pages_path

    # Generate summary.md
    summary_path = output_dir / "summary.md"
    _write_summary_markdown(report, summary_path)
    report_files["summary"] = summary_path

    logger.info(f"Reports generated in {output_dir}")
    return report_files


def _write_keep_pages_json(report: CoverageReport, output_path: Path) -> None:
    """Write keep_pages.json (pages needing extraction)."""
    data = {
        "pdf_source": report.pdf_source,
        "yaml_sources": report.yaml_sources,
        "total_pages": len(report.keep_pages),
        "pages": [p.model_dump(exclude_none=True) for p in report.keep_pages],
    }

    with open(output_path, "w") as f:
        json.dump(data, f, indent=2)

    logger.info(f"Wrote {output_path} ({len(report.keep_pages)} pages)")


def _write_discard_pages_json(report: CoverageReport, output_path: Path) -> None:
    """Write discard_pages.json (pages to skip)."""
    data = {
        "pdf_source": report.pdf_source,
        "total_pages": len(report.discard_pages),
        "pages": [p.model_dump(exclude_none=True) for p in report.discard_pages],
    }

    with open(output_path, "w") as f:
        json.dump(data, f, indent=2)

    logger.info(f"Wrote {output_path} ({len(report.discard_pages)} pages)")


def _write_summary_markdown(report: CoverageReport, output_path: Path) -> None:
    """Write summary.md (human-readable report)."""
    stats = report.summary_stats

    markdown = f"""# PDF Coverage Validation Summary

## Overview

- **PDF Source:** `{report.pdf_source}`
- **YAML Sources:** {len(report.yaml_sources)} files
- **Total PDF Pages:** {report.total_pdf_pages}
- **Similarity Threshold:** {report.threshold}%

## Coverage Statistics

| Metric | Count | Percentage |
|--------|-------|------------|
| Already Covered | {stats['covered_pages']} | {stats['covered_pages'] / report.total_pdf_pages * 100:.1f}% |
| Blank Pages | {stats['blank_pages']} | {stats['blank_pages'] / report.total_pdf_pages * 100:.1f}% |
| Needs Extraction | {stats['needs_extraction']} | {stats['needs_extraction'] / report.total_pdf_pages * 100:.1f}% |
| **Total** | **{report.total_pdf_pages}** | **100.0%** |

## Results

### ✅ Pages Already Covered ({stats['covered_pages']} pages)

High similarity to existing YAML content - extraction not needed.

{_format_page_list(report.discard_pages, "already_covered")}

### ⚠️ Pages Needing Extraction ({stats['needs_extraction']} pages)

Low similarity to YAML content - likely contains new material.

{_format_page_list(report.keep_pages, "needs_extraction")}

### 📄 Blank Pages ({stats['blank_pages']} pages)

Minimal text content - safe to skip.

{_format_page_list(report.discard_pages, "blank")}

## Action Items

### Priority 1: Extract New Content

Process the {stats['needs_extraction']} pages marked "needs_extraction":

```bash
# Page numbers to process:
{_format_page_numbers(report.keep_pages)}
```

### Priority 2: Verify Coverage

Review pages with borderline scores (70-90% similarity) to ensure accuracy:

{_format_borderline_pages(report)}

## YAML Sources Used

{_format_yaml_sources(report.yaml_sources)}

---

*Generated by PDF Coverage Validator*
"""

    with open(output_path, "w") as f:
        f.write(markdown)

    logger.info(f"Wrote {output_path}")


def _format_page_list(
    pages: list[PageClassification],
    reason: str,
    limit: int = 20,
) -> str:
    """Format page list for markdown."""
    filtered = [p for p in pages if p.reason == reason]

    if not filtered:
        return "*None*"

    # Show first N pages
    shown = filtered[:limit]
    remaining = len(filtered) - len(shown)

    lines = []
    for page in shown:
        score_text = f"(score: {page.score}%)" if page.score is not None else ""
        conf_text = (
            f"(confidence: {page.confidence}%)"
            if page.confidence is not None
            else ""
        )
        len_text = f"({page.text_length} chars)" if page.text_length is not None else ""

        detail = score_text or conf_text or len_text
        lines.append(f"- Page {page.page} {detail}")

    if remaining > 0:
        lines.append(f"- *... and {remaining} more pages*")

    return "\n".join(lines)


def _format_page_numbers(pages: list[PageClassification]) -> str:
    """Format page numbers as comma-separated list."""
    if not pages:
        return "# (none)"

    page_nums = sorted([p.page for p in pages])

    # Group consecutive pages into ranges
    ranges: list[str] = []
    start = page_nums[0]
    end = page_nums[0]

    for num in page_nums[1:]:
        if num == end + 1:
            end = num
        else:
            if start == end:
                ranges.append(str(start))
            else:
                ranges.append(f"{start}-{end}")
            start = end = num

    # Add final range
    if start == end:
        ranges.append(str(start))
    else:
        ranges.append(f"{start}-{end}")

    return ", ".join(ranges)


def _format_borderline_pages(report: CoverageReport) -> str:
    """Format list of borderline pages (70-90% similarity)."""
    borderline = [
        p
        for p in report.discard_pages + report.keep_pages
        if p.score is not None and 70 <= p.score <= 90
    ]

    if not borderline:
        return "*No borderline pages found*"

    lines = ["Pages with scores between 70-90%:", ""]
    for page in sorted(borderline, key=lambda p: p.score or 0, reverse=True):
        lines.append(f"- Page {page.page}: {page.score}% similarity")

    return "\n".join(lines)


def _format_yaml_sources(sources: list[str]) -> str:
    """Format YAML sources list."""
    if not sources:
        return "*None*"

    return "\n".join(f"- `{s}`" for s in sources)
